-- Supabase schema for Google News FR dashboard
-- À coller dans Supabase > SQL Editor > New query > Run.

create table if not exists public.articles (
  uid text primary key,
  published timestamp without time zone,
  date text,
  hour text,
  source text,
  source_domain text,
  media_group text,
  title text,
  summary text default '',
  canonical_title text,
  link text,
  first_query_kind text,
  first_query_label text,
  first_query_day text,
  all_query_labels text,
  occurrences_in_feeds integer default 1,
  created_at timestamp without time zone
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  wave integer,
  kind text,
  label text,
  base_query text,
  day text,
  date_from text,
  date_to text,
  status integer,
  raw_entries integer,
  kept_before_dedup integer,
  error text,
  url text,
  query text,
  finished_at timestamp without time zone
);

create index if not exists idx_articles_published on public.articles(published desc);
create index if not exists idx_articles_source on public.articles(source);
create index if not exists idx_articles_media_group on public.articles(media_group);
create index if not exists idx_articles_date on public.articles(date);
create index if not exists idx_attempts_finished_at on public.attempts(finished_at desc);

create or replace view public.article_stats as
select
  count(*)::bigint as total_articles,
  count(distinct source)::bigint as total_sources,
  min(published) as first_article,
  max(published) as last_article
from public.articles;

create or replace view public.media_sources as
select source, count(*)::bigint as count
from public.articles
where coalesce(source, '') <> ''
group by source
order by source asc;

create or replace view public.media_groups as
select coalesce(media_group, 'Autres médias') as media_group, count(*)::bigint as count
from public.articles
group by coalesce(media_group, 'Autres médias')
order by count desc;

create or replace view public.top_sources as
select source, count(*)::bigint as count
from public.articles
group by source
order by count desc, source asc
limit 20;

alter table public.articles enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "Public read articles" on public.articles;
create policy "Public read articles"
on public.articles
for select
to anon
using (true);

-- Attempts stay private. GitHub Actions uses the service_role key, which bypasses RLS.

grant usage on schema public to anon;
grant select on public.articles to anon;
grant select on public.article_stats to anon;
grant select on public.media_sources to anon;
grant select on public.media_groups to anon;
grant select on public.top_sources to anon;

create extension if not exists pgcrypto;

-- Email alert filters created from the public dashboard.
create table if not exists public.alert_filters (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  email text not null,
  label text,
  keywords jsonb not null default '[]'::jsonb,
  match_mode text not null default 'any' check (match_mode in ('any', 'all')),
  scope text not null default 'all' check (scope in ('all', 'top_100', 'national', 'local')),
  active boolean not null default true,
  last_checked_at timestamp with time zone default now(),
  first_test_sent_at timestamp with time zone,
  constraint alert_filters_email_shape check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
  constraint alert_filters_keywords_array check (jsonb_typeof(keywords) = 'array'),
  constraint alert_filters_keywords_size check (jsonb_array_length(keywords) between 1 and 12)
);

create table if not exists public.alert_deliveries (
  filter_id uuid not null references public.alert_filters(id) on delete cascade,
  article_uid text not null references public.articles(uid) on delete cascade,
  sent_at timestamp with time zone default now(),
  primary key (filter_id, article_uid)
);

alter table public.alert_filters add column if not exists first_test_sent_at timestamp with time zone;

create index if not exists idx_alert_filters_active on public.alert_filters(active, last_checked_at);
create index if not exists idx_alert_deliveries_filter on public.alert_deliveries(filter_id, sent_at desc);

alter table public.alert_filters enable row level security;
alter table public.alert_deliveries enable row level security;

drop policy if exists "Public create alert filters" on public.alert_filters;
create policy "Public create alert filters"
on public.alert_filters
for insert
to anon
with check (
  active = true
  and jsonb_typeof(keywords) = 'array'
  and jsonb_array_length(keywords) between 1 and 12
  and match_mode in ('any', 'all')
  and scope in ('all', 'top_100', 'national', 'local')
);

-- Alert filters and deliveries stay private after creation. GitHub Actions uses service_role.
grant insert on public.alert_filters to anon;
grant select, insert, update, delete on public.alert_filters to service_role;
grant select, insert, update, delete on public.alert_deliveries to service_role;

-- Private management token used by the dashboard to show/delete only alerts created from the same browser.
alter table public.alert_filters add column if not exists manage_token text;
alter table public.alert_filters add column if not exists first_test_sent_at timestamp with time zone;
create index if not exists idx_alert_filters_manage_token on public.alert_filters(manage_token) where manage_token is not null;

create table if not exists public.alert_test_requests (
  id bigint generated by default as identity primary key,
  filter_id uuid not null references public.alert_filters(id) on delete cascade,
  manage_token text not null,
  created_at timestamp with time zone default now(),
  processed_at timestamp with time zone,
  status text default 'pending',
  error text
);

create index if not exists idx_alert_test_requests_pending on public.alert_test_requests(processed_at, created_at);
alter table public.alert_test_requests enable row level security;
grant select, insert, update, delete on public.alert_test_requests to service_role;

drop function if exists public.create_alert_filter(text, text, jsonb, text, text, text);
create function public.create_alert_filter(
  p_label text,
  p_email text,
  p_keywords jsonb,
  p_match_mode text,
  p_scope text,
  p_manage_token text
)
returns table (
  id uuid,
  created_at timestamp with time zone,
  email text,
  label text,
  keywords jsonb,
  match_mode text,
  scope text,
  active boolean,
  first_test_sent_at timestamp with time zone
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_manage_token is null or length(p_manage_token) < 32 then
    raise exception 'manage_token invalid';
  end if;
  if p_email is null or p_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'email invalid';
  end if;
  if jsonb_typeof(p_keywords) <> 'array' or jsonb_array_length(p_keywords) < 1 or jsonb_array_length(p_keywords) > 12 then
    raise exception 'keywords invalid';
  end if;
  if p_match_mode not in ('any', 'all') then
    raise exception 'match_mode invalid';
  end if;
  if p_scope not in ('all', 'top_100', 'national', 'local') then
    raise exception 'scope invalid';
  end if;

  return query
  with inserted as (
    insert into public.alert_filters(email, label, keywords, match_mode, scope, active, manage_token, last_checked_at)
    values (p_email, nullif(p_label, ''), p_keywords, p_match_mode, p_scope, true, p_manage_token, now())
    returning alert_filters.id as filter_id, alert_filters.created_at, alert_filters.email, alert_filters.label, alert_filters.keywords, alert_filters.match_mode, alert_filters.scope, alert_filters.active, alert_filters.first_test_sent_at
  ), request as (
    insert into public.alert_test_requests(filter_id, manage_token)
    select inserted.filter_id, p_manage_token from inserted
    returning 1
  )
  select inserted.filter_id, inserted.created_at, inserted.email, inserted.label, inserted.keywords, inserted.match_mode, inserted.scope, inserted.active, inserted.first_test_sent_at
  from inserted;
end;
$$;

drop function if exists public.list_alert_filters(text[]);
create function public.list_alert_filters(p_manage_tokens text[])
returns table (
  id uuid,
  created_at timestamp with time zone,
  email text,
  label text,
  keywords jsonb,
  match_mode text,
  scope text,
  active boolean,
  first_test_sent_at timestamp with time zone
)
language sql
security definer
set search_path = public
as $$
  select af.id, af.created_at, af.email, af.label, af.keywords, af.match_mode, af.scope, af.active, af.first_test_sent_at
  from public.alert_filters af
  where af.active = true
    and af.manage_token is not null
    and af.manage_token = any(p_manage_tokens)
  order by af.created_at desc;
$$;

drop function if exists public.delete_alert_filter(uuid, text);
create function public.delete_alert_filter(p_id uuid, p_manage_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.alert_filters
  where id = p_id and manage_token = p_manage_token;
  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$$;

drop function if exists public.request_alert_test(uuid, text);
create function public.request_alert_test(p_id uuid, p_manage_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.alert_test_requests(filter_id, manage_token)
  select af.id, p_manage_token
  from public.alert_filters af
  where af.id = p_id and af.manage_token = p_manage_token and af.active = true;
  return found;
end;
$$;


-- Public writes now go through security-definer functions, not direct table inserts.
revoke insert on public.alert_filters from anon;
drop policy if exists "Public create alert filters" on public.alert_filters;

grant execute on function public.create_alert_filter(text, text, jsonb, text, text, text) to anon;
grant execute on function public.list_alert_filters(text[]) to anon;
grant execute on function public.delete_alert_filter(uuid, text) to anon;
grant execute on function public.request_alert_test(uuid, text) to anon;

