-- Supabase schema for Google News FR dashboard
-- À coller dans Supabase > SQL Editor > New query > Run.

create table if not exists public.articles (
  uid text primary key,
  published timestamp without time zone,
  date text,
  hour text,
  source text,
  source_domain text,
  media_group text,
  title text,
  summary text default '',
  canonical_title text,
  link text,
  first_query_kind text,
  first_query_label text,
  first_query_day text,
  all_query_labels text,
  occurrences_in_feeds integer default 1,
  created_at timestamp without time zone
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  wave integer,
  kind text,
  label text,
  base_query text,
  day text,
  date_from text,
  date_to text,
  status integer,
  raw_entries integer,
  kept_before_dedup integer,
  error text,
  url text,
  query text,
  finished_at timestamp without time zone
);

create index if not exists idx_articles_published on public.articles(published desc);
create index if not exists idx_articles_source on public.articles(source);
create index if not exists idx_articles_media_group on public.articles(media_group);
create index if not exists idx_articles_date on public.articles(date);
create index if not exists idx_attempts_finished_at on public.attempts(finished_at desc);

create or replace view public.article_stats as
select
  count(*)::bigint as total_articles,
  count(distinct source)::bigint as total_sources,
  min(published) as first_article,
  max(published) as last_article
from public.articles;

create or replace view public.media_sources as
select source, count(*)::bigint as count
from public.articles
where coalesce(source, '') <> ''
group by source
order by source asc;

create or replace view public.media_groups as
select coalesce(media_group, 'Autres médias') as media_group, count(*)::bigint as count
from public.articles
group by coalesce(media_group, 'Autres médias')
order by count desc;

create or replace view public.top_sources as
select source, count(*)::bigint as count
from public.articles
group by source
order by count desc, source asc
limit 20;

alter table public.articles enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "Public read articles" on public.articles;
create policy "Public read articles"
on public.articles
for select
to anon
using (true);

-- Attempts stay private. GitHub Actions uses the service_role key, which bypasses RLS.

grant usage on schema public to anon;
grant select on public.articles to anon;
grant select on public.article_stats to anon;
grant select on public.media_sources to anon;
grant select on public.media_groups to anon;
grant select on public.top_sources to anon;

create extension if not exists pgcrypto;

-- Email alert filters created from the public dashboard.
create table if not exists public.alert_filters (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  email text not null,
  label text,
  keywords jsonb not null default '[]'::jsonb,
  match_mode text not null default 'any' check (match_mode in ('any', 'all')),
  scope text not null default 'all' check (scope in ('all', 'top_100', 'national', 'local')),
  active boolean not null default true,
  last_checked_at timestamp with time zone default now(),
  constraint alert_filters_email_shape check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
  constraint alert_filters_keywords_array check (jsonb_typeof(keywords) = 'array'),
  constraint alert_filters_keywords_size check (jsonb_array_length(keywords) between 1 and 12)
);

create table if not exists public.alert_deliveries (
  filter_id uuid not null references public.alert_filters(id) on delete cascade,
  article_uid text not null references public.articles(uid) on delete cascade,
  sent_at timestamp with time zone default now(),
  primary key (filter_id, article_uid)
);

create index if not exists idx_alert_filters_active on public.alert_filters(active, last_checked_at);
create index if not exists idx_alert_deliveries_filter on public.alert_deliveries(filter_id, sent_at desc);

alter table public.alert_filters enable row level security;
alter table public.alert_deliveries enable row level security;

drop policy if exists "Public create alert filters" on public.alert_filters;
create policy "Public create alert filters"
on public.alert_filters
for insert
to anon
with check (
  active = true
  and jsonb_typeof(keywords) = 'array'
  and jsonb_array_length(keywords) between 1 and 12
  and match_mode in ('any', 'all')
  and scope in ('all', 'top_100', 'national', 'local')
);

-- Alert filters and deliveries stay private after creation. GitHub Actions uses service_role.
grant insert on public.alert_filters to anon;
grant select, insert, update, delete on public.alert_filters to service_role;
grant select, insert, update, delete on public.alert_deliveries to service_role;

