#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"

DASHBOARD = r'''<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Google News FR - Live Dashboard</title>
  <script src="supabase_config.js"></script>
  <style>
    :root{--bg:#f7f6f2;--surface:#fff;--ink:#171717;--muted:#69655d;--soft:#ede9df;--line:#dedbd2;--accent:#0f766e;--accent2:#b45309;--danger:#b91c1c;--focus:rgba(15,118,110,.18);--side:#20231f;--side2:#2b2e29}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0}button,input,select,textarea{font:inherit}button{cursor:pointer}.app{min-height:100vh;display:grid;grid-template-columns:304px minmax(0,1fr)}
    .side{position:sticky;top:0;height:100vh;padding:28px 22px;background:var(--side);color:#f8f6ef;border-right:1px solid rgba(255,255,255,.08);display:flex;flex-direction:column;gap:24px}.brand{display:grid;gap:8px}.brand small{color:#b9b5a9;font-size:12px;text-transform:uppercase;letter-spacing:.14em}h1{margin:0;font-size:25px;line-height:1.08;font-weight:760}.updated{color:#c9c4b8;font-size:13px;line-height:1.45}.nav{display:grid;gap:8px}.nav button{height:42px;border:1px solid rgba(255,255,255,.1);border-radius:8px;background:transparent;color:#eee9dc;text-align:left;padding:0 12px}.nav button.active{background:#f8f6ef;color:#1e211d;border-color:#f8f6ef}.sideStats{display:grid;gap:10px}.stat{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.055);border-radius:8px;padding:14px}.stat .num{font-size:28px;line-height:1;font-weight:780}.stat .label{margin-top:6px;color:#c9c4b8;font-size:12px}.sideFoot{margin-top:auto;color:#aaa396;font-size:12px;line-height:1.5}
    main{padding:26px 30px 44px;min-width:0}.view{display:none}.view.active{display:block}.topbar{display:grid;grid-template-columns:minmax(240px,1fr) 210px 220px 170px;gap:10px;align-items:center;margin-bottom:16px}.searchBox,.filterBox{position:relative}.filterIcon{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--muted);font-size:13px;pointer-events:none}.searchBox input,select,.field input,.field textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:var(--surface);outline:none}.searchBox input,select{height:48px}.searchBox input{padding:0 44px 0 16px}.searchBox input:focus,select:focus,.field input:focus,.field textarea:focus{border-color:var(--accent);box-shadow:0 0 0 4px var(--focus)}.filterBox select{padding-left:34px}.kbd{position:absolute;right:12px;top:50%;transform:translateY(-50%);color:var(--muted);font-size:12px;border:1px solid var(--line);border-radius:6px;padding:2px 6px;background:#faf9f5}
    .summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:16px}.metric{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:16px;min-width:0}.metric b{display:block;font-size:22px;line-height:1.1}.metric span{display:block;margin-top:6px;color:var(--muted);font-size:12px}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:16px;align-items:start}.panel,.rail,.formPanel{background:var(--surface);border:1px solid var(--line);border-radius:8px}.panelHead{min-height:54px;padding:14px 16px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px}.panelHead h2{margin:0;font-size:15px;font-weight:720}.panelHead p{margin:0;color:var(--muted);font-size:13px}.list{display:grid}
    .article{display:grid;grid-template-columns:118px minmax(0,1fr);gap:16px;padding:16px;border-bottom:1px solid var(--line)}.article:last-child{border-bottom:0}.date{color:var(--muted);font-size:12px;line-height:1.45;white-space:nowrap}.title{margin:0 0 8px;font-size:17px;line-height:1.3;font-weight:720}.title a{color:var(--ink);text-decoration:none}.title a:hover{color:var(--accent)}.dek{margin:0 0 10px;color:#4d4942;font-size:14px;line-height:1.45}.meta{display:flex;flex-wrap:wrap;gap:8px;align-items:center;color:var(--muted);font-size:12px}.pill{display:inline-flex;min-height:24px;align-items:center;border:1px solid var(--line);border-radius:999px;padding:3px 8px;color:#4c4942;background:#fbfaf6;overflow-wrap:anywhere}.empty{padding:42px 16px;text-align:center;color:var(--muted)}
    .pager{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 16px;border-top:1px solid var(--line)}.pager button,.ghost,.primary{border:1px solid var(--line);background:var(--surface);border-radius:8px;min-height:38px;padding:0 14px}.primary{background:var(--accent);border-color:var(--accent);color:white;font-weight:700}.ghost:hover,.pager button:hover:not(:disabled){border-color:var(--accent);color:var(--accent)}.pager button:disabled{opacity:.45;cursor:default}.rail{padding:16px;display:grid;gap:18px}.rail h3{margin:0 0 10px;font-size:13px;text-transform:uppercase;color:var(--muted);letter-spacing:.08em}.barRow{display:grid;gap:6px;margin:10px 0}.barLabel{display:flex;justify-content:space-between;gap:10px;font-size:12px;color:#3d3a35}.bar{height:8px;border-radius:999px;background:#f0efea;overflow:hidden}.bar span{display:block;height:100%;background:var(--accent);border-radius:inherit}.chipList{display:flex;flex-wrap:wrap;gap:7px}.chip{border:1px solid var(--line);background:#fbfaf6;border-radius:999px;padding:6px 9px;font-size:12px;color:#3d3a35}.chip:hover{border-color:var(--accent);color:var(--accent)}
    .alertHero{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(280px,.85fr);gap:16px;align-items:stretch;margin-bottom:16px}.intro{background:var(--side);color:#f8f6ef;border-radius:8px;padding:24px;display:grid;align-content:space-between;min-height:250px}.intro h2{margin:0;font-size:30px;line-height:1.05}.intro p{margin:12px 0 0;color:#d9d3c5;line-height:1.5;max-width:690px}.introStats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}.introStats div{border:1px solid rgba(255,255,255,.12);border-radius:8px;padding:12px}.introStats b{display:block;font-size:20px}.introStats span{display:block;margin-top:5px;color:#c8c1b3;font-size:12px}.formPanel{padding:18px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:7px}.field.full{grid-column:1/-1}.field label{font-size:12px;color:#5a554d;font-weight:700}.field input,.field textarea{min-height:46px;padding:10px 12px}.field textarea{resize:vertical;min-height:86px;line-height:1.4}.keywordRow{display:grid;grid-template-columns:minmax(0,1fr) 42px;gap:8px;margin-bottom:8px}.iconBtn{width:42px;height:42px;border-radius:8px;border:1px solid var(--line);background:#fbfaf6}.hint{color:var(--muted);font-size:12px;line-height:1.45}.actions{display:flex;gap:10px;align-items:center;justify-content:flex-end;margin-top:14px}.status{min-height:20px;font-size:13px;color:var(--muted);margin-top:12px}.status.ok{color:#047857}.status.err{color:var(--danger)}.choiceRow{display:grid;grid-template-columns:1fr 1fr;gap:10px}.choice{border:1px solid var(--line);border-radius:8px;padding:12px;background:#fbfaf6}.choice strong{display:block;font-size:13px}.choice span{display:block;margin-top:4px;font-size:12px;color:var(--muted);line-height:1.35}.alertRail{display:grid;gap:16px}.miniList{display:grid;gap:10px}.miniItem{border:1px solid var(--line);border-radius:8px;padding:12px;background:#fff}.miniItem b{display:block;font-size:13px}.miniItem span{display:block;margin-top:5px;font-size:12px;color:var(--muted);line-height:1.35}.alertsBoard{margin-top:16px}.alertCards{display:grid;gap:10px}.alertCard{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:start;padding:14px 16px;border-bottom:1px solid var(--line)}.alertCard:last-child{border-bottom:0}.alertCard h3{margin:0 0 7px;font-size:15px}.alertCard p{margin:0;color:var(--muted);font-size:13px;line-height:1.45}.alertCard .tools{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.dangerBtn{border:1px solid #efc7c7;color:#991b1b;background:#fff7f7;border-radius:8px;min-height:36px;padding:0 12px}.smallBtn{border:1px solid var(--line);background:#fbfaf6;border-radius:8px;min-height:36px;padding:0 12px}.tagLine{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.tag{border:1px solid var(--line);border-radius:999px;padding:3px 8px;background:#fbfaf6;color:#4c4942;font-size:12px}
    @media(max-width:1040px){.app{grid-template-columns:1fr}.side{position:relative;height:auto}.workspace,.alertHero{grid-template-columns:1fr}}@media(max-width:760px){main{padding:16px}.topbar,.summary,.formGrid,.introStats,.choiceRow{grid-template-columns:1fr}.article{grid-template-columns:1fr;gap:8px}.date{white-space:normal}.intro h2{font-size:25px}}
  </style>
</head>
<body>
<div class="app"><aside class="side"><div class="brand"><small>Veille Google News</small><h1>France Ultra Recall</h1><div class="updated" id="updatedAt">Base Supabase live</div></div><nav class="nav"><button id="tabArticles" class="active" type="button">Articles</button><button id="tabAlerts" type="button">Alertes email</button></nav><div class="sideStats"><div class="stat"><div class="num" id="statArticles">-</div><div class="label">articles uniques</div></div><div class="stat"><div class="num" id="statSources">-</div><div class="label">sources distinctes</div></div><div class="stat"><div class="num" id="statMatches">-</div><div class="label">résultats filtrés</div></div></div><div class="sideFoot">Dashboard connecté à Supabase. La collecte tourne chaque heure via GitHub Actions.</div></aside>
<main>
<section id="viewArticles" class="view active"><div class="topbar"><div class="searchBox"><input id="searchInput" type="search" placeholder="Rechercher un mot clé, une source, un sujet..." autocomplete="off" autofocus><span class="kbd">⌘K</span></div><div class="filterBox"><span class="filterIcon">◇</span><select id="sourceFilter"><option value="">Tous les médias</option></select></div><div class="filterBox"><span class="filterIcon">◇</span><select id="groupFilter"><option value="">Tous les groupes</option></select></div><select id="sortMode"><option value="newest">Plus récents</option><option value="oldest">Plus anciens</option><option value="source">Source A-Z</option></select></div>
<section class="summary"><div class="metric"><b id="metricPeriod">-</b><span>période couverte</span></div><div class="metric"><b id="metricLast">-</b><span>dernier article</span></div><div class="metric"><b id="metricDb">Supabase</b><span>base active</span></div><div class="metric"><b id="metricPage">20</b><span>articles par page</span></div></section>
<div class="workspace"><section class="panel"><div class="panelHead"><div><h2>Articles</h2><p id="resultLine">Chargement...</p></div></div><div class="list" id="articleList"><div class="empty">Chargement des articles...</div></div><div class="pager"><button id="prevBtn">Précédent</button><span id="pageInfo">Page 1</span><button id="nextBtn">Suivant</button></div></section><aside class="rail"><section><h3>Top sources</h3><div id="topSources"></div></section><section><h3>Mots rapides</h3><div class="chipList" id="quickTerms"></div></section></aside></div></section>
<section id="viewAlerts" class="view"><div class="alertHero"><div class="intro"><div><small>Alertes automatiques</small><h2>Créez une veille email ciblée, livrée à chaque passage horaire.</h2><p>Chaque filtre surveille les titres et les chapeaux. Dès que le robot trouve de nouveaux articles correspondants, un email récapitulatif part avec les liens.</p></div><div class="introStats"><div><b>1h</b><span>rythme d’envoi</span></div><div><b>100</b><span>médias majeurs inclus</span></div><div><b>AND / OR</b><span>logique de mots clés</span></div></div></div><aside class="alertRail"><div class="miniItem"><b>Recherche</b><span>Titres et résumés sont analysés ensemble, avec un ou plusieurs mots clés.</span></div><div class="miniItem"><b>Périmètre médias</b><span>Tous les journaux, top 100 France, presse nationale ou presse locale.</span></div><div class="miniItem"><b>Envoi</b><span>Les emails partent pendant le workflow GitHub Actions, après la mise à jour Supabase.</span></div></aside></div>
<form id="alertForm" class="formPanel"><div class="panelHead" style="padding:0 0 14px;border-bottom:0"><div><h2>Créer un filtre</h2><p>Les alertes commencent sur les prochains nouveaux articles, pas sur tout l’historique.</p></div></div><div class="formGrid"><div class="field"><label for="alertLabel">Nom du filtre</label><input id="alertLabel" maxlength="80" placeholder="Ex: IA santé locale"></div><div class="field"><label for="alertEmail">Adresse email</label><input id="alertEmail" type="email" required maxlength="254" placeholder="vous@exemple.com"></div><div class="field full"><label>Mots clés</label><div id="keywordRows"></div><button class="ghost" id="addKeyword" type="button">Ajouter un mot clé</button><div class="hint">Exemples: “cyberattaque”, “hôpital”, “levée de fonds”.</div></div><div class="field"><label for="matchMode">Logique</label><select id="matchMode"><option value="any">Au moins un mot clé</option><option value="all">Tous les mots clés</option></select></div><div class="field"><label for="scopeMode">Médias surveillés</label><select id="scopeMode"><option value="all">Tous les journaux</option><option value="top_100">Top 100 médias français</option><option value="national">Presse nationale</option><option value="local">Presse locale et régionale</option></select></div><div class="field full"><div class="choiceRow"><div class="choice"><strong>Top 100</strong><span>Liste de grands médias français: quotidiens, TV/radio, économie, tech, magazines et régionaux majeurs.</span></div><div class="choice"><strong>National / local</strong><span>Réutilise les groupes médias déjà constitués dans la base.</span></div></div></div></div><div class="actions"><span class="hint">Vous recevrez uniquement les nouveautés.</span><button class="primary" type="submit">Créer l’alerte</button></div><div id="alertStatus" class="status"></div></form><section class="panel alertsBoard"><div class="panelHead"><div><h2>Alertes enregistrées</h2><p id="alertsLine">Chargement...</p></div><button class="ghost" id="refreshAlerts" type="button">Actualiser</button></div><div id="alertsList" class="alertCards"><div class="empty">Chargement des alertes...</div></div></section></section>
</main></div>
<script>
const CFG=window.SUPABASE_CONFIG||{};const API=(CFG.url||'').replace(/\/$/,'')+'/rest/v1';const KEY=CFG.anonKey||'';const PAGE_SIZE=20;const fmt=new Intl.NumberFormat('fr-FR');let page=1,total=0;const $=id=>document.getElementById(id);const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function compactDate(value){if(!value)return '-';const [d,t='']=String(value).replace('T',' ').split(' ');const bits=d.split('-');if(bits.length!==3)return value;return `${bits[2]}/${bits[1]}/${bits[0]} ${t.slice(0,5)}`.trim()}async function supa(path,opts={}){const res=await fetch(API+path,{...opts,headers:{apikey:KEY,Authorization:'Bearer '+KEY,...(opts.headers||{})}});if(!res.ok)throw new Error(await res.text());return res}
async function rpc(name,payload){const r=await supa('/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.status===204?null:await r.json()}
function setTab(name){const articles=name==='articles';$('viewArticles').classList.toggle('active',articles);$('viewAlerts').classList.toggle('active',!articles);$('tabArticles').classList.toggle('active',articles);$('tabAlerts').classList.toggle('active',!articles)}$('tabArticles').addEventListener('click',()=>setTab('articles'));$('tabAlerts').addEventListener('click',()=>setTab('alerts'));
function applyParams(base){const params=new URLSearchParams();params.set('select',base.select);if(base.order)params.set('order',base.order);const source=$('sourceFilter').value,group=$('groupFilter').value,q=$('searchInput').value.trim();if(source)params.set('source','eq.'+source);if(group)params.set('media_group','eq.'+group);if(q){const pat='*'+q.replace(/[,*()]/g,' ')+'*';params.set('or',`(title.ilike.${pat},summary.ilike.${pat},source.ilike.${pat},source_domain.ilike.${pat},media_group.ilike.${pat})`)}return params.toString()}
async function loadStats(){const r=await supa('/article_stats?select=*');const stats=(await r.json())[0]||{};$('statArticles').textContent=fmt.format(stats.total_articles||0);$('statSources').textContent=fmt.format(stats.total_sources||0);$('metricPeriod').textContent=stats.first_article&&stats.last_article?`${compactDate(stats.first_article).slice(0,10)} → ${compactDate(stats.last_article).slice(0,10)}`:'-';$('metricLast').textContent=compactDate(stats.last_article);$('updatedAt').textContent='Mis à jour automatiquement'}
async function loadFilters(){const [srcRes,grpRes,topRes]=await Promise.all([supa('/media_sources?select=source&order=source.asc'),supa('/media_groups?select=media_group,count'),supa('/top_sources?select=source,count')]);const sources=await srcRes.json();$('sourceFilter').innerHTML='<option value="">Tous les médias</option>'+sources.map(s=>`<option value="${esc(s.source)}">${esc(s.source)}</option>`).join('');const order=['Presse nationale','Presse locale et régionale','TV / radio','Économie','Tech / numérique','Médias spécialisés','Outre-mer','Portails / agrégateurs','Autres médias'];const groups=(await grpRes.json()).sort((a,b)=>order.indexOf(a.media_group)-order.indexOf(b.media_group));$('groupFilter').innerHTML='<option value="">Tous les groupes</option>'+groups.map(g=>`<option value="${esc(g.media_group)}">${esc(g.media_group)} (${fmt.format(g.count)})</option>`).join('');const top=await topRes.json();const max=top.length?top[0].count:1;$('topSources').innerHTML=top.slice(0,10).map(r=>`<div class="barRow"><div class="barLabel"><span>${esc(r.source)}</span><b>${fmt.format(r.count)}</b></div><div class="bar"><span style="width:${Math.max(4,Math.round((r.count/max)*100))}%"></span></div></div>`).join('')}
async function loadArticles(){const sort=$('sortMode').value;const order=sort==='oldest'?'published.asc':sort==='source'?'source.asc,published.desc':'published.desc';const qs=applyParams({select:'published,date,hour,source,source_domain,media_group,title,summary,link,occurrences_in_feeds,first_query_kind,first_query_label',order});const from=(page-1)*PAGE_SIZE,to=from+PAGE_SIZE-1;const r=await supa('/articles?'+qs,{headers:{Prefer:'count=exact',Range:`${from}-${to}`}});const range=r.headers.get('content-range')||'0-0/0';total=Number(range.split('/')[1]||0);const rows=await r.json();$('statMatches').textContent=fmt.format(total);$('resultLine').textContent=`${fmt.format(total)} résultat${total>1?'s':''}`;render(rows)}
function render(rows){if(!rows.length){$('articleList').innerHTML='<div class="empty">Aucun article ne correspond à cette recherche.</div>'}else{$('articleList').innerHTML=rows.map(a=>`<article class="article"><div class="date">${compactDate(a.published)}<br>${esc(a.hour||'')}</div><div><h3 class="title"><a href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a></h3>${a.summary?`<p class="dek">${esc(a.summary)}</p>`:''}<div class="meta"><span class="pill">${esc(a.source||'Source inconnue')}</span>${a.source_domain?`<span>${esc(a.source_domain)}</span>`:''}<span>${esc(a.media_group||'Autres médias')}</span><span>${esc(a.first_query_kind||'')}</span><span>${fmt.format(a.occurrences_in_feeds||1)} apparition${Number(a.occurrences_in_feeds||1)>1?'s':''}</span></div></div></article>`).join('')}const maxPage=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(page,maxPage);$('pageInfo').textContent=`Page ${page} / ${maxPage}`;$('prevBtn').disabled=page<=1;$('nextBtn').disabled=page>=maxPage}
function refresh(){page=1;loadArticles().catch(e=>{$('articleList').innerHTML='<div class="empty">Erreur Supabase: '+esc(e.message)+'</div>'})}$('searchInput').addEventListener('input',()=>{clearTimeout(window._t);window._t=setTimeout(refresh,350)});$('sourceFilter').addEventListener('change',refresh);$('groupFilter').addEventListener('change',refresh);$('sortMode').addEventListener('change',refresh);$('prevBtn').addEventListener('click',()=>{if(page>1){page--;loadArticles()}});$('nextBtn').addEventListener('click',()=>{if(page<Math.ceil(total/PAGE_SIZE)){page++;loadArticles()}});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){$('searchInput').focus();e.preventDefault()}});const quick=['politique','justice','incendie','accident','santé','économie','agriculture','cyberattaque','météo','école'];$('quickTerms').innerHTML=quick.map(t=>`<button class="chip" data-term="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{$('searchInput').value=b.dataset.term;refresh()}));
function keywordRow(value=''){const div=document.createElement('div');div.className='keywordRow';div.innerHTML=`<input class="kw" maxlength="80" placeholder="Mot clé" value="${esc(value)}"><button class="iconBtn" type="button" title="Retirer">×</button>`;div.querySelector('button').addEventListener('click',()=>{if(document.querySelectorAll('.kw').length>1)div.remove();else div.querySelector('input').value='' });return div}function addKeyword(value=''){$('keywordRows').appendChild(keywordRow(value))}$('addKeyword').addEventListener('click',()=>addKeyword());addKeyword();
const ALERT_STORE='googleNewsAlertTokens.v2';
function loadAlertTokens(){try{return JSON.parse(localStorage.getItem(ALERT_STORE)||'{}')}catch{return {}}}
function saveAlertTokens(tokens){localStorage.setItem(ALERT_STORE,JSON.stringify(tokens))}
function makeToken(){const a=new Uint8Array(24);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function scopeLabel(v){return {all:'Tous les journaux',top_100:'Top 100 médias français',national:'Presse nationale',local:'Presse locale et régionale'}[v]||v}
function modeLabel(v){return v==='all'?'Tous les mots':'Au moins un mot'}
function renderAlerts(rows){$('alertsLine').textContent=`${rows.length} alerte${rows.length>1?'s':''} sur ce navigateur`;if(!rows.length){$('alertsList').innerHTML='<div class="empty">Aucune alerte enregistrée sur ce navigateur.</div>';return}$('alertsList').innerHTML=rows.map(a=>`<article class="alertCard" data-id="${esc(a.id)}"><div><h3>${esc(a.label||'Alerte sans nom')}</h3><p>${esc(a.email||'')} · ${esc(scopeLabel(a.scope))} · ${esc(modeLabel(a.match_mode))}</p><div class="tagLine">${(a.keywords||[]).map(k=>`<span class="tag">${esc(k)}</span>`).join('')}<span class="tag">${a.first_test_sent_at?'Test envoyé':'Test en attente'}</span></div></div><div class="tools"><button class="smallBtn" data-action="test">Envoyer test</button><button class="dangerBtn" data-action="delete">Supprimer</button></div></article>`).join('')}
async function loadAlerts(){const tokens=loadAlertTokens();const values=Object.values(tokens);if(!values.length){renderAlerts([]);return}try{const rows=await rpc('list_alert_filters',{p_manage_tokens:values});renderAlerts(rows||[])}catch(err){$('alertsLine').textContent='Schéma Supabase à mettre à jour';$('alertsList').innerHTML='<div class="empty">Lancez le SQL alertes mis à jour dans Supabase.</div>';console.error(err)}}
$('refreshAlerts').addEventListener('click',loadAlerts);
$('alertsList').addEventListener('click',async e=>{const btn=e.target.closest('button');if(!btn)return;const card=btn.closest('.alertCard');const id=card?.dataset.id;const token=loadAlertTokens()[id];if(!id||!token)return;btn.disabled=true;try{if(btn.dataset.action==='delete'){await rpc('delete_alert_filter',{p_id:id,p_manage_token:token});const tokens=loadAlertTokens();delete tokens[id];saveAlertTokens(tokens);await loadAlerts()}else{await rpc('request_alert_test',{p_id:id,p_manage_token:token});btn.textContent='Test demandé'}}catch(err){btn.textContent='Erreur';console.error(err)}finally{setTimeout(()=>{btn.disabled=false;if(btn.dataset.action==='test')btn.textContent='Envoyer test'},2200)}});
$('alertForm').addEventListener('submit',async e=>{e.preventDefault();const status=$('alertStatus');status.className='status';status.textContent='Création de l’alerte...';const keywords=[...document.querySelectorAll('.kw')].map(i=>i.value.trim()).filter(Boolean).slice(0,12);const email=$('alertEmail').value.trim();if(!keywords.length){status.className='status err';status.textContent='Ajoutez au moins un mot clé.';return}const token=makeToken();const payload={p_label:$('alertLabel').value.trim()||keywords.join(' / '),p_email:email,p_keywords:keywords,p_match_mode:$('matchMode').value,p_scope:$('scopeMode').value,p_manage_token:token};try{const rows=await rpc('create_alert_filter',payload);const row=(rows||[])[0];if(row?.id){const tokens=loadAlertTokens();tokens[row.id]=token;saveAlertTokens(tokens)}status.className='status ok';status.textContent='Alerte créée et test demandé. Elle apparaît ci-dessous.';$('alertForm').reset();$('keywordRows').innerHTML='';addKeyword();await loadAlerts()}catch(err){status.className='status err';status.textContent='Impossible de créer l’alerte. Le SQL Supabase doit être mis à jour.';console.error(err)}});
loadAlerts();
Promise.all([loadStats(),loadFilters()]).then(loadArticles).catch(e=>{$('articleList').innerHTML='<div class="empty">Configuration Supabase manquante ou invalide.</div>';console.error(e)});
</script>
</body>
</html>
'''


def require_env(name: str) -> str:
    value = os.environ.get(name, '').strip()
    if not value:
        raise SystemExit(f"Variable manquante: {name}")
    return value


def main() -> None:
    if PUBLIC.exists():
        shutil.rmtree(PUBLIC)
    PUBLIC.mkdir(parents=True)
    supabase_url = require_env('SUPABASE_URL').rstrip('/')
    anon_key = require_env('SUPABASE_ANON_KEY')
    (PUBLIC / 'index.html').write_text(DASHBOARD, encoding='utf-8')
    (PUBLIC / 'dashboard_google_news.html').write_text(DASHBOARD, encoding='utf-8')
    config = 'window.SUPABASE_CONFIG = ' + json.dumps({'url': supabase_url, 'anonKey': anon_key}, ensure_ascii=False) + ';\n'
    (PUBLIC / 'supabase_config.js').write_text(config, encoding='utf-8')
    (PUBLIC / 'status.json').write_text(json.dumps({'generated_at_utc': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'backend': 'supabase', 'features': ['alerts']}, indent=2), encoding='utf-8')
    (PUBLIC / '.nojekyll').write_text('', encoding='utf-8')
    print(f"Supabase site prepared in {PUBLIC}")


if __name__ == '__main__':
    main()
